"""Tenant-safe identity, session, and workspace authorization contracts."""

from .models import (
    AccessSecret,
    AccountAccessExport,
    AccountMembershipExport,
    AuthenticatedSession,
    AuditAction,
    AuditCategory,
    AuditEvent,
    AuditOutcome,
    ChangeMembershipRole,
    CreateWorkspace,
    DeleteWorkspace,
    ErrorCode,
    GrantMembership,
    IssuedSession,
    Membership,
    Permission,
    RevokeMembership,
    RetentionReport,
    ROLE_PERMISSIONS,
    Role,
    SessionEvidence,
    VerifiedIdentity,
    UpdateWorkspace,
    Workspace,
    WorkspaceContext,
    WorkspaceSelection,
    WorkspaceSummary,
    WorkspaceAccessError,
    permissions_for_role,
)
from .service import WorkspaceAccessService

__all__ = [
    "AccessSecret",
    "AccountAccessExport",
    "AccountMembershipExport",
    "AuthenticatedSession",
    "AuditAction",
    "AuditCategory",
    "AuditEvent",
    "AuditOutcome",
    "ChangeMembershipRole",
    "CreateWorkspace",
    "DeleteWorkspace",
    "ErrorCode",
    "GrantMembership",
    "IssuedSession",
    "Membership",
    "Permission",
    "RevokeMembership",
    "RetentionReport",
    "ROLE_PERMISSIONS",
    "Role",
    "SessionEvidence",
    "VerifiedIdentity",
    "UpdateWorkspace",
    "Workspace",
    "WorkspaceContext",
    "WorkspaceSelection",
    "WorkspaceSummary",
    "WorkspaceAccessError",
    "WorkspaceAccessService",
    "permissions_for_role",
]
